version: '3.8'

services:
  arch:
    build: ./arch
    tty: true
    stdin_open: true
    container_name: ArchEnv
    ports:
      - 80:80
    volumes:
      - type: bind 
        source: /home/angel/Documents/pizzeriaAPI/
        target: /home/developer/proyecto
        bind:
          propagation: rslave
      - neovimdata:/home/developer/.local
    depends_on:
      - database
    networks:
      - devnetwork

  database:
    # build: ./postgres
    # tty: false
    # container_name: database
    # environment:
    #   POSTGRES_DB: biblioteca
    #   POSTGRES_USER: admin
    #   POSTGRES_PASSWORD: 1234   
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    build: ./mysql
    tty: false
    container_name: database
    environment:
      MYSQL_DATABASE: pizzeria
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
        - devnetwork

networks:
  devnetwork:
    driver: bridge

volumes:
  # pgdata:
  mysqldata:
  neovimdata:
